### ISSUE TITLE
TCAPProviderImpl getNextSeqControl

### ISSUE THREAD

**Issue by wrongt** [RestComm/jss7#212] opened 2017-02-22 07:17 UTC
In parallel environment generation of new seqControl number can jump this condition:
`if (!seqControl.compareAndSet(256, 1))` 

> compareAndSet(int expect, int update)
>Atomically sets the value to the given updated value if the current value == the expected value.

and seqControl value continue to be incremented with values bigger then 256, and this cause  the following exception: 
`java.lang.ArrayIndexOutOfBoundsException: 264
	at org.mobicents.protocols.ss7.m3ua.impl.AspFactoryImpl.write(AspFactoryImpl.java:491)
	at org.mobicents.protocols.ss7.m3ua.impl.AsImpl.write(AsImpl.java:654)
	at org.mobicents.protocols.ss7.m3ua.impl.M3UAManagementImpl.sendMessage(M3UAManagementImpl.java:1168)
	at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.send(SccpRoutingControl.java:258)
	at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.sendMessageToMtp(SccpRoutingControl.java:841)
	at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.route(SccpRoutingControl.java:767)
	at org.mobicents.protocols.ss7.sccp.impl.SccpRoutingControl.routeMssgFromSccpUser(SccpRoutingControl.java:192)
	at org.mobicents.protocols.ss7.sccp.impl.SccpStackImpl.send(SccpStackImpl.java:716)
	at org.mobicents.protocols.ss7.sccp.impl.SccpProviderImpl.send(SccpProviderImpl.java:148)
	at org.mobicents.protocols.ss7.tcap.TCAPProviderImpl.send(TCAPProviderImpl.java:359)
	at org.mobicents.protocols.ss7.tcap.DialogImpl.send(DialogImpl.java:562)
	at org.mobicents.protocols.ss7.map.MAPProviderImpl.fireTCBegin(MAPProviderImpl.java:1796)
	at org.mobicents.protocols.ss7.map.MAPDialogImpl.send(MAPDialogImpl.java:353)`

**Comment by vetss** [comment] 2017-02-24 07:10
Hello @wrongt 

I think it is a bug in the current implementation, we need to check. Thanks for a report.
The root issue for the threading model is: https://github.com/RestComm/jss7/issues/110

**Comment by vetss** [comment] 2017-02-27 12:15
Hello @wrongt 

Fixed by commits:
https://github.com/RestComm/jss7/commit/ce80d10ab4b45144e6b28602898d3f8ddf06f1c1 - TCAP
https://github.com/RestComm/jss7/commit/28fc522758f2d3796191b7cfaa0973cee3bf455c - TCAP ANSI

Can you please test if the issue is fixed at your side ?

**Closed by vetss** 2017-02-27 12:15 UTC
Labels: bug

**Comment by wrongt** [comment] 2017-03-03 19:58
Thank you @vetss  now it's ok.
